networks:
  dockerapi-dev:
    driver: bridge

services:
  dockerapi:
    image: dockerapi:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: VkApi/Dockerfile
    ports:
      - "8000:80"
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=vkapidb;username=vkapiuser;password=vkapipassword"
    networks:
      - dockerapi-dev
  
  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      # - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "vkapiuser"
      POSTGRES_PASSWORD: "vkapipassword"
      POSTGRES_DB: "vkapidb"
    networks:
      - dockerapi-dev
volumes:
  db_volume: